### ISSUE TITLE
English language

### ISSUE THREAD

**Issue by fmarkf** [kugelm/WBT201-Android#1]
Hello,

First of all thank your for the great App! It seems to work fine. 

May I ask you please to compile another .apk file with English UI and messages please? Also, it would be very nice if I can specify output directory. My default OsmAnd folder for tracks is on the External SD card, so I'd like to download tracks there to eliminate manual copying from default location.

Thank you!
Mark

**Comment by kugelm** [comment]
Hi Mark,

thanks for your friendly feedback. I didn't expect someone else to use this combination of Android device plus GPS logger to be honest...
1) the easy part ist the english localization (should work now but not tested)
2) selecting a folder for the downloaded tracks will be a bit more effort - but not too much. Work is in progress :-)
By the way: If you are using OsmAnd I expected the app to behave exactly as you described. My tracks folder is on a (virtual) External SD card as well. Anyway, I will implement a path select option soon. Just for my information (and perhaps debugging): What is the full path to your tracks folder?

Cheers 
Thomas

**Comment by fmarkf** [comment]
Hi Thomas,

Thanks for quick reply. Yeah, I was very excited when I found your great project online. :)

1) I tested English version - works perfectly! Is there any reason to not translate to English Debug output?

2) If it will make your life easier, may be you want to create some settings file where path can be specified manually. Of course 'Folder selection UI' will be much more convenient to use. :)

FYI: Currently it downloads tracks to the WBT201 folder on internal SD card.

Thanks again for your help!
Mark

**Comment by kugelm** [comment]
Hi!

1) didn't translate 100% in the first try, should be fine now (except the fact that I'm not a native speaker...)
2) I adapted some code for a simple directory chooser dialog. You can activate it from the options menu upper right corner. It's not very convenient but will do the job for the moment. Hope that helps.

I will close this issue. If you find bugs are have other suggestions I will be glad to hear again from you. If I have some sparse time I'll clean up a bit and think about implementing new features.

Cheers
Thomas

**Comment by fmarkf** [comment]
Hi Thomas!

Thank you very much! It works!! Now it is so much easier to select a folder.
You did an amazing app - simple and functional! Good job!

> If I have some sparse time I'll clean up a bit and think about 
> implementing new features.
> Sounds good!

For me the most important feature (from your list) would be:
- read out and set configuration parameters on the logger

Thank you again!
Mark
