### ISSUE TITLE
Needed help with using "JJ-Connect Registrator" clone of WBT201

### ISSUE THREAD

**Issue by pgavrilov** [kugelm/WBT201-Android#3]
Hi.

I have device "JJ-Connect Registrator", it's a clone of WBT201 model.
But it have different bluetooth name, so WBT201 App doesn't see it.
WBT201 App connection log shows the next messages:

```
track download directory:
/storage/sdcard0/osmand/tracks
Known BT devices:
 ( Registrator 2x )
Did'nt succeed!
```

Please add this string to the list of suitable BT devices.

**Comment by kugelm** [comment]
Hi!

I simply added the device string to the list of accepted bluetooth devices as suggested. Because
I don't have access to such a device you should verify the change by installing the new apk and give me feedback. Thanks.

**Comment by pgavrilov** [comment]
I confirm.
Problem solved.
